defmodule MagicBattleground.Components.FactoryType do
  @moduledoc """
  Belongs to Factory entities, stores an atom value which is a constant term that can be used
  to lookup the resource type and quantity generated by the Factory.
  """
  use ECSx.Component,
    value: :atom
end
